version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=96430409
      - MYSQL_DATABASE=accordous
      - MYSQL_USER=accordous
      - MYSQL_PASSWORD=accordous

  laravel:
    image: ambientum/php:7.2-nginx
    container_name: laravel
    volumes:
      - .:/var/www/app
    ports:
      - 3000:8080
    depends_on:
      - mysql
